// Mocks generated by Mockito 5.4.6 from annotations
// in blockchain_fyp/test/error_handling/error_handling_tests.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:blockchain_fyp/services/biometric_service.dart' as _i6;
import 'package:blockchain_fyp/services/contract_service.dart' as _i8;
import 'package:blockchain_fyp/services/secure_storage_service.dart' as _i7;
import 'package:blockchain_fyp/services/totp_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:otp/otp.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TOTPService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTOTPService extends _i1.Mock implements _i2.TOTPService {
  MockTOTPService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get timeOffset => (super.noSuchMethod(
        Invocation.getter(#timeOffset),
        returnValue: 0,
      ) as int);

  @override
  bool get isTimeSyncRecent => (super.noSuchMethod(
        Invocation.getter(#isTimeSyncRecent),
        returnValue: false,
      ) as bool);

  @override
  String generateSecret() => (super.noSuchMethod(
        Invocation.method(
          #generateSecret,
          [],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #generateSecret,
            [],
          ),
        ),
      ) as String);

  @override
  String generateTOTP(
    String? secret, {
    _i4.Algorithm? algorithm = _i4.Algorithm.SHA1,
    int? timeOffset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateTOTP,
          [secret],
          {
            #algorithm: algorithm,
            #timeOffset: timeOffset,
          },
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #generateTOTP,
            [secret],
            {
              #algorithm: algorithm,
              #timeOffset: timeOffset,
            },
          ),
        ),
      ) as String);

  @override
  bool verifyTOTP(
    String? secret,
    String? code, {
    _i4.Algorithm? algorithm = _i4.Algorithm.SHA1,
    int? timeWindow,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyTOTP,
          [
            secret,
            code,
          ],
          {
            #algorithm: algorithm,
            #timeWindow: timeWindow,
          },
        ),
        returnValue: false,
      ) as bool);

  @override
  String generateTOTPURI(
    String? secret,
    String? accountName, {
    String? issuer,
    _i4.Algorithm? algorithm = _i4.Algorithm.SHA1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateTOTPURI,
          [
            secret,
            accountName,
          ],
          {
            #issuer: issuer,
            #algorithm: algorithm,
          },
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #generateTOTPURI,
            [
              secret,
              accountName,
            ],
            {
              #issuer: issuer,
              #algorithm: algorithm,
            },
          ),
        ),
      ) as String);

  @override
  List<String> generateBackupCodes() => (super.noSuchMethod(
        Invocation.method(
          #generateBackupCodes,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  bool verifyBackupCode(
    String? code,
    List<String>? availableCodes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyBackupCode,
          [
            code,
            availableCodes,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  int getRemainingTime() => (super.noSuchMethod(
        Invocation.method(
          #getRemainingTime,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  bool isCodeExpired(
    String? secret,
    String? code, {
    _i4.Algorithm? algorithm = _i4.Algorithm.SHA1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isCodeExpired,
          [
            secret,
            code,
          ],
          {#algorithm: algorithm},
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> syncTime() => (super.noSuchMethod(
        Invocation.method(
          #syncTime,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool isValidSecret(String? secret) => (super.noSuchMethod(
        Invocation.method(
          #isValidSecret,
          [secret],
        ),
        returnValue: false,
      ) as bool);

  @override
  Map<String, dynamic> getConfiguration() => (super.noSuchMethod(
        Invocation.method(
          #getConfiguration,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i5.Future<void> testTOTP() => (super.noSuchMethod(
        Invocation.method(
          #testTOTP,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> generateSecretSafe() => (super.noSuchMethod(
        Invocation.method(
          #generateSecretSafe,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #generateSecretSafe,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> generateTOTPSafe(
    String? secret, {
    _i4.Algorithm? algorithm = _i4.Algorithm.SHA1,
    int? timeOffset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateTOTPSafe,
          [secret],
          {
            #algorithm: algorithm,
            #timeOffset: timeOffset,
          },
        ),
        returnValue: _i5.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #generateTOTPSafe,
            [secret],
            {
              #algorithm: algorithm,
              #timeOffset: timeOffset,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<bool> verifyTOTPSafe(
    String? secret,
    String? code, {
    _i4.Algorithm? algorithm = _i4.Algorithm.SHA1,
    int? timeWindow,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyTOTPSafe,
          [
            secret,
            code,
          ],
          {
            #algorithm: algorithm,
            #timeWindow: timeWindow,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<String> generateTOTPURISafe(
    String? secret,
    String? accountName, {
    String? issuer,
    _i4.Algorithm? algorithm = _i4.Algorithm.SHA1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateTOTPURISafe,
          [
            secret,
            accountName,
          ],
          {
            #issuer: issuer,
            #algorithm: algorithm,
          },
        ),
        returnValue: _i5.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #generateTOTPURISafe,
            [
              secret,
              accountName,
            ],
            {
              #issuer: issuer,
              #algorithm: algorithm,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<List<String>> generateBackupCodesSafe() => (super.noSuchMethod(
        Invocation.method(
          #generateBackupCodesSafe,
          [],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<bool> verifyBackupCodeSafe(
    String? code,
    List<String>? availableCodes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyBackupCodeSafe,
          [
            code,
            availableCodes,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> syncTimeSafe() => (super.noSuchMethod(
        Invocation.method(
          #syncTimeSafe,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> getRemainingTimeSafe() => (super.noSuchMethod(
        Invocation.method(
          #getRemainingTimeSafe,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<bool> isCodeExpiredSafe(
    String? secret,
    String? code, {
    _i4.Algorithm? algorithm = _i4.Algorithm.SHA1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isCodeExpiredSafe,
          [
            secret,
            code,
          ],
          {#algorithm: algorithm},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> isValidSecretSafe(String? secret) => (super.noSuchMethod(
        Invocation.method(
          #isValidSecretSafe,
          [secret],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<Map<String, dynamic>> getConfigurationSafe() =>
      (super.noSuchMethod(
        Invocation.method(
          #getConfigurationSafe,
          [],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> testTOTPSafe() => (super.noSuchMethod(
        Invocation.method(
          #testTOTPSafe,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  Map<String, dynamic> getErrorStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getErrorStatistics,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void clearErrorHistory() => super.noSuchMethod(
        Invocation.method(
          #clearErrorHistory,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [BiometricService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBiometricService extends _i1.Mock implements _i6.BiometricService {
  MockBiometricService() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i7.SecureStorageService {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> storeTOTPSecret(String? secret) => (super.noSuchMethod(
        Invocation.method(
          #storeTOTPSecret,
          [secret],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getTOTPSecret() => (super.noSuchMethod(
        Invocation.method(
          #getTOTPSecret,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> setBiometricEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setBiometricEnabled,
          [enabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isBiometricEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isBiometricEnabled,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> storeBackupCodes(List<String>? codes) => (super.noSuchMethod(
        Invocation.method(
          #storeBackupCodes,
          [codes],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<String>> getBackupCodes() => (super.noSuchMethod(
        Invocation.method(
          #getBackupCodes,
          [],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<bool> areBackupCodesExpired() => (super.noSuchMethod(
        Invocation.method(
          #areBackupCodesExpired,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> useBackupCode(String? code) => (super.noSuchMethod(
        Invocation.method(
          #useBackupCode,
          [code],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<DateTime?> getLastBackupCodeUsed() => (super.noSuchMethod(
        Invocation.method(
          #getLastBackupCodeUsed,
          [],
        ),
        returnValue: _i5.Future<DateTime?>.value(),
      ) as _i5.Future<DateTime?>);

  @override
  _i5.Future<void> setUser2FAStatus(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setUser2FAStatus,
          [enabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isUser2FAEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isUser2FAEnabled,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setTOTPAlgorithm(String? algorithm) => (super.noSuchMethod(
        Invocation.method(
          #setTOTPAlgorithm,
          [algorithm],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> getTOTPAlgorithm() => (super.noSuchMethod(
        Invocation.method(
          #getTOTPAlgorithm,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #getTOTPAlgorithm,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> setTimeWindowTolerance(int? tolerance) =>
      (super.noSuchMethod(
        Invocation.method(
          #setTimeWindowTolerance,
          [tolerance],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> getTimeWindowTolerance() => (super.noSuchMethod(
        Invocation.method(
          #getTimeWindowTolerance,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> storeTimeSyncData(
    DateTime? lastSync,
    int? timeOffset,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeTimeSyncData,
          [
            lastSync,
            timeOffset,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>?> getTimeSyncData() => (super.noSuchMethod(
        Invocation.method(
          #getTimeSyncData,
          [],
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> clear2FAData() => (super.noSuchMethod(
        Invocation.method(
          #clear2FAData,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> storeSecureData(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeSecureData,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getSecureData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getSecureData,
          [key],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> deleteSecureData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #deleteSecureData,
          [key],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, String>> getAllStoredData() => (super.noSuchMethod(
        Invocation.method(
          #getAllStoredData,
          [],
        ),
        returnValue: _i5.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i5.Future<Map<String, String>>);

  @override
  _i5.Future<bool> isStorageAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isStorageAvailable,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<Map<String, dynamic>> getStorageStats() => (super.noSuchMethod(
        Invocation.method(
          #getStorageStats,
          [],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> testStorage() => (super.noSuchMethod(
        Invocation.method(
          #testStorage,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> storeTOTPSecretSafe(String? secret) => (super.noSuchMethod(
        Invocation.method(
          #storeTOTPSecretSafe,
          [secret],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getTOTPSecretSafe() => (super.noSuchMethod(
        Invocation.method(
          #getTOTPSecretSafe,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> storeBackupCodesSafe(List<String>? codes) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeBackupCodesSafe,
          [codes],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<String>> getBackupCodesSafe() => (super.noSuchMethod(
        Invocation.method(
          #getBackupCodesSafe,
          [],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<bool> useBackupCodeSafe(String? code) => (super.noSuchMethod(
        Invocation.method(
          #useBackupCodeSafe,
          [code],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setUser2FAStatusSafe(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setUser2FAStatusSafe,
          [enabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isUser2FAEnabledSafe() => (super.noSuchMethod(
        Invocation.method(
          #isUser2FAEnabledSafe,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setBiometricEnabledSafe(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBiometricEnabledSafe,
          [enabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isBiometricEnabledSafe() => (super.noSuchMethod(
        Invocation.method(
          #isBiometricEnabledSafe,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> storeSecureDataSafe(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeSecureDataSafe,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getSecureDataSafe(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getSecureDataSafe,
          [key],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> deleteSecureDataSafe(String? key) => (super.noSuchMethod(
        Invocation.method(
          #deleteSecureDataSafe,
          [key],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clear2FADataSafe() => (super.noSuchMethod(
        Invocation.method(
          #clear2FADataSafe,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isStorageAvailableSafe() => (super.noSuchMethod(
        Invocation.method(
          #isStorageAvailableSafe,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<Map<String, dynamic>> getStorageStatsSafe() => (super.noSuchMethod(
        Invocation.method(
          #getStorageStatsSafe,
          [],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> testStorageSafe() => (super.noSuchMethod(
        Invocation.method(
          #testStorageSafe,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  Map<String, dynamic> getErrorStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getErrorStatistics,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void clearErrorHistory() => super.noSuchMethod(
        Invocation.method(
          #clearErrorHistory,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ContractService].
///
/// See the documentation for Mockito's code generation for more information.
class MockContractService extends _i1.Mock implements _i8.ContractService {
  MockContractService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get contractAddress => (super.noSuchMethod(
        Invocation.getter(#contractAddress),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#contractAddress),
        ),
      ) as String);

  @override
  String getFunctionData(String? functionName) => (super.noSuchMethod(
        Invocation.method(
          #getFunctionData,
          [functionName],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #getFunctionData,
            [functionName],
          ),
        ),
      ) as String);

  @override
  _i5.Future<String> register(String? privateKey) => (super.noSuchMethod(
        Invocation.method(
          #register,
          [privateKey],
        ),
        returnValue: _i5.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #register,
            [privateKey],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> login(String? privateKey) => (super.noSuchMethod(
        Invocation.method(
          #login,
          [privateKey],
        ),
        returnValue: _i5.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #login,
            [privateKey],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> registerWithAddress(String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerWithAddress,
          [address],
        ),
        returnValue: _i5.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #registerWithAddress,
            [address],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> loginWithAddress(String? address) => (super.noSuchMethod(
        Invocation.method(
          #loginWithAddress,
          [address],
        ),
        returnValue: _i5.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #loginWithAddress,
            [address],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<bool> isRegistered(String? address) => (super.noSuchMethod(
        Invocation.method(
          #isRegistered,
          [address],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<String> enable2FA(
    String? address,
    List<String>? backupCodes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #enable2FA,
          [
            address,
            backupCodes,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #enable2FA,
            [
              address,
              backupCodes,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<bool> verify2FA(
    String? address,
    String? code,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verify2FA,
          [
            address,
            code,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<String> disable2FA(String? address) => (super.noSuchMethod(
        Invocation.method(
          #disable2FA,
          [address],
        ),
        returnValue: _i5.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #disable2FA,
            [address],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<bool> is2FAEnabled(String? address) => (super.noSuchMethod(
        Invocation.method(
          #is2FAEnabled,
          [address],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> getBackupCodeCount(String? address) => (super.noSuchMethod(
        Invocation.method(
          #getBackupCodeCount,
          [address],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> getFailedAttempts(String? address) => (super.noSuchMethod(
        Invocation.method(
          #getFailedAttempts,
          [address],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<bool> isLockedOut(String? address) => (super.noSuchMethod(
        Invocation.method(
          #isLockedOut,
          [address],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> getRemainingLockoutTime(String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRemainingLockoutTime,
          [address],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<String> regenerateBackupCodes(
    String? address,
    List<String>? newBackupCodes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #regenerateBackupCodes,
          [
            address,
            newBackupCodes,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #regenerateBackupCodes,
            [
              address,
              newBackupCodes,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<int> estimateGas(
    String? functionName,
    List<dynamic>? parameters,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #estimateGas,
          [
            functionName,
            parameters,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> getCurrentGasPrice() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentGasPrice,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> testRegisterAndLogin() => (super.noSuchMethod(
        Invocation.method(
          #testRegisterAndLogin,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> getContractInfo() => (super.noSuchMethod(
        Invocation.method(
          #getContractInfo,
          [],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> enable2FASafe(
    String? privateKey,
    List<String>? backupCodes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #enable2FASafe,
          [
            privateKey,
            backupCodes,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #enable2FASafe,
            [
              privateKey,
              backupCodes,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<bool> verify2FASafe(
    String? privateKey,
    String? code,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verify2FASafe,
          [
            privateKey,
            code,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<String> disable2FASafe(String? privateKey) => (super.noSuchMethod(
        Invocation.method(
          #disable2FASafe,
          [privateKey],
        ),
        returnValue: _i5.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #disable2FASafe,
            [privateKey],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<bool> is2FAEnabledSafe(String? address) => (super.noSuchMethod(
        Invocation.method(
          #is2FAEnabledSafe,
          [address],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> getBackupCodeCountSafe(String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBackupCodeCountSafe,
          [address],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> getFailedAttemptsSafe(String? address) => (super.noSuchMethod(
        Invocation.method(
          #getFailedAttemptsSafe,
          [address],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<bool> isLockedOutSafe(String? address) => (super.noSuchMethod(
        Invocation.method(
          #isLockedOutSafe,
          [address],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> getRemainingLockoutTimeSafe(String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRemainingLockoutTimeSafe,
          [address],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<String> regenerateBackupCodesSafe(
    String? privateKey,
    List<String>? newBackupCodes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #regenerateBackupCodesSafe,
          [
            privateKey,
            newBackupCodes,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #regenerateBackupCodesSafe,
            [
              privateKey,
              newBackupCodes,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> registerSafe(String? privateKey) => (super.noSuchMethod(
        Invocation.method(
          #registerSafe,
          [privateKey],
        ),
        returnValue: _i5.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #registerSafe,
            [privateKey],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> loginSafe(String? privateKey) => (super.noSuchMethod(
        Invocation.method(
          #loginSafe,
          [privateKey],
        ),
        returnValue: _i5.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #loginSafe,
            [privateKey],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<bool> isRegisteredSafe(String? address) => (super.noSuchMethod(
        Invocation.method(
          #isRegisteredSafe,
          [address],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  Map<String, dynamic> getErrorStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getErrorStatistics,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void clearErrorHistory() => super.noSuchMethod(
        Invocation.method(
          #clearErrorHistory,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> disposeSafe() => (super.noSuchMethod(
        Invocation.method(
          #disposeSafe,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
