name: blockchain_fyp
description: A Blockchain-Based Secure File Sharing and Communication System
version: 1.0.0+1
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  web3dart: ^2.7.2
  walletconnect_flutter_v2: ^2.2.5
  get_it: ^7.7.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2
  http: ^1.2.2
  hex: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/contract_abi.json