name: blockchain_fyp
description: A Blockchain-Based Secure File Sharing and Communication System
version: 1.0.0+1
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  web3dart: ^2.7.2
  walletconnect_flutter_v2: ^2.2.5
  get_it: ^7.7.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2
  http: ^1.2.2
  share_plus: ^7.2.1
  hex: ^0.2.0
  file_picker: ^8.0.7
  image_picker: ^1.0.7
  dio: ^5.8.0+1
  open_file: ^3.3.2
  open_file_macos: ^0.0.1
  path_provider: ^2.1.2
  ffi: ^2.1.0
  otp: ^3.2.0
  crypto: ^3.0.3
  local_auth: ^2.1.7
  flutter_secure_storage: ^9.0.0
  uuid: ^4.2.1
  connectivity_plus: ^5.0.2
  mailer: ^6.0.1
  email_validator: ^2.1.17
  flutter_dotenv: ^5.1.0
  app_links: ^3.4.2
  record: ^5.1.2
  permission_handler: ^11.3.1
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.7

dependency_overrides:
  record_linux: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/contract_abi.json
    - assets/logo.png
    - assets/chat_illustration.png
    - assets/ProfileIcon.png
    - assets/team_illustration.webp
    - .env